export const planCommands = [
  'kernel.workspace.open', 'kernel.workspace.rename', 'kernel.workspace.forget', 'kernel.workspace.preview.create',
  'kernel.trust.grant', 'kernel.trust.revoke', 'kernel.extension.stage', 'kernel.extension.install',
  'kernel.extension.enable', 'kernel.extension.disable', 'kernel.extension.reload', 'kernel.extension.rollback',
  'kernel.extension.unquarantine', 'kernel.extension.uninstall', 'kernel.preset.import', 'kernel.preset.apply.stage',
  'kernel.preset.apply', 'kernel.preset.update', 'kernel.preset.save', 'kernel.preset.delete', 'kernel.config.set',
  'kernel.secret.set', 'kernel.secret.clear', 'kernel.cancel', 'kernel.message.retry', 'kernel.message.discard',
  'kernel.dev.project.create', 'kernel.dev.project.delete', 'kernel.dev.file.write', 'kernel.dev.file.delete',
  'kernel.dev.build', 'kernel.dev.folder.stage', 'kernel.shutdown', 'kernel.llm.complete', 'kernel.llm.models.refresh',
  'kernel.llm.defaults.set', 'kernel.user.preferences.set', 'kernel.notification.read', 'kernel.notification.dismiss',
  'kernel.notifications.read-all', 'kernel.notifications.mute', 'ui.toast', 'ui.notify', 'ui.dismiss', 'ui.navigate',
  'agent.session.create', 'agent.chat.start', 'agent.send', 'agent.child.send', 'agent.inject', 'agent.step',
  'agent.tool.record', 'agent.approval.answer', 'agent.tool.call.review', 'agent.tool.review.release', 'agent.guards.set',
  'agent.prompt.section.set', 'agent.prompt.section.remove', 'agent.cancel', 'agent.turn.finalize', 'agent.turn.expire',
  'agent.compact', 'agent.session.export', 'agent.session.rename', 'agent.session.set-model',
  'agent.session.set-tool-mode', 'agent.session.close', 'agent.session.delete', 'agent.session.fork', 'agent.child.run',
  'agent.retention.run', 'llm-providers.login.start', 'llm-providers.login.finish', 'llm-providers.login.expire',
  'shell.exec', 'shell.job.finish', 'shell.kill', 'fs.write', 'fs.edit', 'fs.dir.create', 'fs.remove', 'todo.create',
  'todo.update', 'todo.complete', 'todo.remove', 'interviewer.ask', 'interviewer.question.answer',
  'interviewer.question.reject', 'interviewer.question.expire', 'local-guard.question.answer', 'builder.plan.propose',
  'builder.approval.answer', 'builder.project.create', 'builder.file.write', 'builder.preset.patch', 'builder.check',
  'builder.test', 'builder.preview.start', 'builder.preview.stop', 'builder.publish', 'builder.rollback', 'pdf.import',
  'pdf.translate', 'pdf.files.prune',
];

export const planQueries = [
  'kernel.health.get', 'kernel.schema.get', 'kernel.validate', 'kernel.extensions.list', 'kernel.extension.get',
  'kernel.workspaces.list', 'kernel.workspace.get', 'kernel.presets.list', 'kernel.preset.get',
  'kernel.preset.current.get', 'kernel.preset.import.preview', 'kernel.preset.export.get', 'kernel.config.get',
  'kernel.trust.preview', 'kernel.trace.get', 'kernel.messages.list', 'kernel.subscribers.list',
  'kernel.processes.list', 'kernel.metrics.get', 'kernel.llm.providers.list', 'kernel.llm.models.list',
  'kernel.llm.defaults.get', 'kernel.llm.tokens.count', 'kernel.llm.usage.get', 'kernel.ui.get', 'kernel.ui.page.get',
  'kernel.ui.translations.get', 'kernel.user.preferences.get', 'kernel.notifications.list',
  'kernel.notifications.count', 'kernel.dev.file.get', 'kernel.dev.files.list', 'agent.history.get',
  'agent.sessions.list', 'agent.session.get', 'agent.tools.list', 'agent.approvals.list', 'agent.reviews.list',
  'agent.prompt.sections.list', 'agent.guards.list', 'agent.slash.list', 'llm-providers.logins.list',
  'shell.jobs.list', 'shell.job.get', 'shell.job.log.get', 'fs.file.get', 'fs.dir.list', 'fs.files.search',
  'todo.list', 'interviewer.questions.list', 'rules.list', 'skills.skill.get', 'builder.schema.search',
  'builder.docs.get', 'builder.approvals.list', 'builder.file.get', 'builder.dir.list', 'builder.versions.list',
  'pdf.files.list', 'pdf.files.count', 'pdf.file.get',
];

export const planEvents = [
  'kernel.started', 'kernel.extension.installed', 'kernel.extension.uninstalled', 'kernel.extension.enabled',
  'kernel.extension.disabled', 'kernel.extension.reloaded', 'kernel.extension.quarantined',
  'kernel.extension.unquarantined', 'kernel.preset.changed', 'kernel.preset.catalog.changed', 'kernel.config.changed',
  'kernel.workspace.opened', 'kernel.workspace.renamed', 'kernel.workspace.forgotten', 'kernel.trust.changed',
  'kernel.message.dead-lettered', 'kernel.llm.models.changed', 'kernel.llm.defaults.changed',
  'kernel.user.preferences.changed', 'kernel.notifications.changed', 'agent.session.created', 'agent.session.updated',
  'agent.session.closed', 'agent.session.deleted', 'agent.session.forked', 'agent.turn.started',
  'agent.turn.completed', 'agent.turn.cancelled', 'agent.turn.failed', 'agent.compacted', 'agent.approval.requested',
  'agent.approval.resolved', 'agent.activated', 'agent.tool.call.created', 'agent.tool.call.completed',
  'agent.entry.appended', 'agent.tokens.generated', 'agent.thinking.generated', 'shell.job.started',
  'shell.job.completed', 'shell.output.written', 'interviewer.question.asked', 'interviewer.question.closed',
  'pdf.imported', 'pdf.translated', 'pdf.progress.updated',
];
