type KernelErrorDefinition = { title: string; retryable: boolean };

export const kernelErrors = {
  VALIDATION_FAILED: { title: 'The request does not match its schema', retryable: false },
  TYPE_NOT_FOUND: { title: 'Unknown message type in this workspace', retryable: false },
  HANDLER_UNAVAILABLE: { title: 'The handling extension is not available', retryable: false },
  NAMESPACE_CONFLICT: { title: 'Another enabled extension owns this namespace', retryable: false },
  CAPABILITY_DENIED: { title: 'The caller lacks the capability or grant', retryable: false },
  CALLER_NOT_ALLOWED: { title: 'This caller may not send this type', retryable: false },
  IDEMPOTENCY_MISMATCH: { title: 'The idempotency key was used for a different request', retryable: false },
  LANE_REENTRANT: { title: 'The command would wait on a lane its own chain holds', retryable: false },
  DEADLINE_EXCEEDED: { title: 'The message deadline passed', retryable: false },
  HANDLER_TIMEOUT: { title: 'The handler ran longer than its timeout', retryable: true },
  CANCELLED: { title: 'The message was cancelled', retryable: false },
  EFFECT_INDETERMINATE: { title: 'A side effect started but its outcome is unknown', retryable: false },
  MESSAGE_DEAD: { title: 'The message failed after its maximum attempts', retryable: false },
  STORAGE_CONFLICT: { title: 'The data changed while the handler ran', retryable: true },
  STORE_NOT_FOUND: { title: 'The document does not exist', retryable: false },
  STORE_RESULT_TOO_LARGE: { title: 'The read returns more than the result cap', retryable: false },
  STEP_DUPLICATE: { title: 'A step name was used twice in one handler run', retryable: false },
  STORAGE_UNAVAILABLE: { title: 'The database is unavailable', retryable: true },
  STORAGE_FULL: { title: 'The disk is full', retryable: false },
  PAYLOAD_TOO_LARGE: { title: 'The payload is over 16 MB', retryable: false },
  QUERY_TIMEOUT: { title: 'The query ran longer than its timeout', retryable: true },
  REPLY_NOT_AWAITING: { title: 'The command is no longer waiting for a reply', retryable: false },
  BLOB_NOT_FOUND: { title: 'The blob does not exist', retryable: false },
  BLOB_TOO_LARGE: { title: 'The blob is over the size limit', retryable: false },
  BLOB_UNSAFE_TYPE: { title: 'The blob type cannot be served inline', retryable: false },
  WORKSPACE_INVALID: { title: 'The workspace is not valid', retryable: false },
  WORKSPACE_ESCAPE: { title: 'The path leaves the workspace', retryable: false },
  WORKSPACE_UNTRUSTED: { title: 'The workspace files are not trusted', retryable: false },
  CONFIG_INVALID: { title: 'The configuration does not match its schema', retryable: false },
  CONFIG_STALE: { title: 'The configuration changed since it was read', retryable: false },
  PRESET_INVALID: { title: 'The preset is not valid', retryable: false },
  PRESET_UNSHAREABLE: { title: 'The preset cannot be shared', retryable: false },
  PRESET_STALE: { title: 'The preset changed since it was read', retryable: false },
  PRESET_SECRET: { title: 'The preset contains a secret', retryable: false },
  PRESET_REFERENCE_MISSING: { title: 'The preset refers to something that does not exist', retryable: false },
  PRESET_REQUIRED: { title: 'The workspace has no applied preset', retryable: false },
  PRESET_INTEGRITY_MISMATCH: { title: 'A package does not match the preset integrity', retryable: false },
  PRESET_READONLY: { title: 'Built-in presets cannot be changed', retryable: false },
  ROUTE_CONFLICT: { title: 'Two active pages have the same route', retryable: false },
  LLM_NOT_CONFIGURED: { title: 'No usable LLM provider is configured', retryable: false },
  LLM_MODEL_NOT_FOUND: { title: 'The model does not exist', retryable: false },
  LLM_THINKING_UNSUPPORTED: { title: 'The model does not support this thinking level', retryable: false },
  LLM_CONTEXT_OVERFLOW: { title: 'The request is too large for the model', retryable: false },
  LLM_CALL_FAILED: { title: 'The LLM provider call failed', retryable: true },
  PROVIDER_CONFLICT: { title: 'Another enabled extension registers this LLM provider', retryable: false },
  EXT_SOURCE_INVALID: { title: 'The extension source is not valid', retryable: false },
  EXT_INTEGRITY: { title: 'The extension snapshot failed its integrity check', retryable: false },
  EXT_MANIFEST_INVALID: { title: 'The extension manifest is not valid', retryable: false },
  EXT_REQUIRES_MISSING: { title: 'Required types or components are missing', retryable: false },
  EXT_IN_USE: { title: 'The extension is in use', retryable: false },
  EXT_QUARANTINED: { title: 'The extension is quarantined', retryable: false },
  EXT_ROLLBACK_BLOCKED: { title: 'The data schema does not allow this rollback', retryable: false },
  EXT_GRANTS_REQUIRED: { title: 'The new version needs new grants', retryable: false },
  SCHEMA_TOO_NEW: { title: 'The stored data is newer than this code', retryable: false },
  MIGRATION_FAILED: { title: 'A data migration failed', retryable: false },
  CONFIRMATION_EXPIRED: { title: 'The confirmation expired or the staged content changed', retryable: true },
  DAEMON_CONFLICT: { title: 'Another kernel owns this home folder', retryable: false },
  HOME_INVALID: { title: 'The home folder holds other files', retryable: false },
  HOST_FORBIDDEN: { title: 'The request Host or Origin is not allowed', retryable: false },
  NOT_FOUND: { title: 'The resource does not exist', retryable: false },
  PORT_UNAVAILABLE: { title: 'No port is free for the kernel', retryable: false },
  KERNEL_STOPPING: { title: 'The kernel is shutting down', retryable: true },
  INTERNAL: { title: 'Unexpected error', retryable: true },
} as const satisfies Record<string, KernelErrorDefinition>;

export type KernelErrorCode = keyof typeof kernelErrors;
