// 13 §13.2: each code's title (ADR 0022) and its description, the table's "When" column (ADR 0111).
type KernelErrorDefinition = { title: string; description: string; retryable: boolean };

export const kernelErrors = {
  VALIDATION_FAILED: { title: 'The request does not match its schema', description: 'The envelope or payload fails its schema; the issues say where.', retryable: false },
  TYPE_NOT_FOUND: { title: 'Unknown message type in this workspace', description: 'No extension registers the message type in this workspace.', retryable: false },
  HANDLER_UNAVAILABLE: { title: 'The handling extension is not available', description: 'The owner is disabled, not enabled in the workspace, quarantined, or reloading (queries only; commands wait).', retryable: false },
  NAMESPACE_CONFLICT: { title: 'Another enabled extension owns this namespace', description: 'A second extension with the same namespace would be enabled in the workspace.', retryable: false },
  CAPABILITY_DENIED: { title: 'The caller lacks the capability or grant', description: 'The caller lacks the capability or grant, including a z.blobId() field naming a blob the sender may not read.', retryable: false },
  CALLER_NOT_ALLOWED: { title: 'This caller may not send this type', description: 'The source does not match the type\'s access: a non-user calling a user type, a person calling an extensions type, anyone but the owner and the kernel calling an internal one, or a user sending ui.*.', retryable: false },
  IDEMPOTENCY_MISMATCH: { title: 'The idempotency key was used for a different request', description: 'The idempotency key was used before with a different request digest.', retryable: false },
  LANE_REENTRANT: { title: 'The command would wait on a lane its own chain holds', description: 'ctx.command into its own lane or an ancestor\'s lane.', retryable: false },
  DEADLINE_EXCEEDED: { title: 'The message deadline passed', description: 'The message\'s deadlineAt passed while it was pending, awaiting, or running.', retryable: false },
  HANDLER_TIMEOUT: { title: 'The handler ran longer than its timeout', description: 'One attempt ran longer than the handler\'s timeoutMs; it counts as an attempt and is retried.', retryable: true },
  CANCELLED: { title: 'The message was cancelled', description: 'The message was cancelled by kernel.cancel or shutdown.', retryable: false },
  EFFECT_INDETERMINATE: { title: 'A side effect started but its outcome is unknown', description: 'A step that is not retry-safe started but did not record, so its side effects are unknown.', retryable: false },
  MESSAGE_DEAD: { title: 'The message failed after its maximum attempts', description: 'The message reached its maximum attempts.', retryable: false },
  STORAGE_CONFLICT: { title: 'The data changed while the handler ran', description: 'An optimistic version check failed or a log seq was taken; normally retried internally.', retryable: true },
  STORE_NOT_FOUND: { title: 'The document does not exist', description: 'A patch named a document that does not exist.', retryable: false },
  STORE_RESULT_TOO_LARGE: { title: 'The read returns more than the result cap', description: 'A find, kv.list, or log.read returns over 5,000 items or 16 MB, or an unindexed scan passes 10,000 documents.', retryable: false },
  STEP_DUPLICATE: { title: 'A step name was used twice in one handler run', description: 'ctx.step was called twice with the same name in one handler run.', retryable: false },
  STORAGE_UNAVAILABLE: { title: 'The database is unavailable', description: 'The disk or the database failed.', retryable: true },
  STORAGE_FULL: { title: 'The disk is full', description: 'The disk is out of space.', retryable: false },
  PAYLOAD_TOO_LARGE: { title: 'The payload is over 16 MB', description: 'The payload is over 16 MB after spill.', retryable: false },
  QUERY_TIMEOUT: { title: 'The query ran longer than its timeout', description: 'A query ran longer than its handler timeout.', retryable: true },
  REPLY_NOT_AWAITING: { title: 'The command is no longer waiting for a reply', description: 'ctx.reply for a command that already has a reply, was cancelled, or passed its deadline.', retryable: false },
  BLOB_NOT_FOUND: { title: 'The blob does not exist', description: 'The blob does not exist.', retryable: false },
  BLOB_TOO_LARGE: { title: 'The blob is over the size limit', description: 'The blob is over the size limit.', retryable: false },
  BLOB_UNSAFE_TYPE: { title: 'The blob type cannot be served inline', description: 'The blob type cannot be served inline.', retryable: false },
  WORKSPACE_INVALID: { title: 'The workspace is not valid', description: 'The workspace does not exist or its path is not valid, or the handler has no workspace.', retryable: false },
  WORKSPACE_ESCAPE: { title: 'The path leaves the workspace', description: 'A path leaves the workspace.', retryable: false },
  WORKSPACE_UNTRUSTED: { title: 'The workspace files are not trusted', description: 'The workspace\'s files are not trusted.', retryable: false },
  CONFIG_INVALID: { title: 'The configuration does not match its schema', description: 'A configuration value does not match its schema.', retryable: false },
  CONFIG_STALE: { title: 'The configuration changed since it was read', description: 'The configuration changed since it was read (revision conflict).', retryable: false },
  PRESET_INVALID: { title: 'The preset is not valid', description: 'The preset does not match its schema.', retryable: false },
  PRESET_UNSHAREABLE: { title: 'The preset cannot be shared', description: 'The preset names a source that cannot be shared (a range, tag, branch, bare name, or file path).', retryable: false },
  PRESET_STALE: { title: 'The preset changed since it was read', description: 'The preset changed since it was read (revision conflict).', retryable: false },
  PRESET_SECRET: { title: 'The preset contains a secret', description: 'The preset contains a secret.', retryable: false },
  PRESET_REFERENCE_MISSING: { title: 'The preset refers to something that does not exist', description: 'The preset refers to a page, contribution, or route that does not exist.', retryable: false },
  PRESET_REQUIRED: { title: 'The workspace has no applied preset', description: 'An extension is enabled in a workspace with no applied preset.', retryable: false },
  PRESET_INTEGRITY_MISMATCH: { title: 'A package does not match the preset integrity', description: 'A downloaded package does not match the preset\'s integrity.', retryable: false },
  PRESET_READONLY: { title: 'Built-in presets cannot be changed', description: 'A built-in preset cannot be changed or deleted.', retryable: false },
  ROUTE_CONFLICT: { title: 'Two active pages have the same route', description: 'Two active pages in a workspace have the same route.', retryable: false },
  LLM_NOT_CONFIGURED: { title: 'No usable LLM provider is configured', description: 'No usable LLM provider or model is configured.', retryable: false },
  LLM_MODEL_NOT_FOUND: { title: 'The model does not exist', description: 'The model does not exist.', retryable: false },
  LLM_THINKING_UNSUPPORTED: { title: 'The model does not support this thinking level', description: 'The model does not support the requested thinking level.', retryable: false },
  LLM_CONTEXT_OVERFLOW: { title: 'The request is too large for the model', description: 'The request is too large for the model.', retryable: false },
  LLM_CALL_FAILED: { title: 'The LLM provider call failed', description: 'The provider call failed (rate limit, network, provider error); carries retryAfterMs when known.', retryable: true },
  PROVIDER_CONFLICT: { title: 'Another enabled extension registers this LLM provider', description: 'Enabling an extension whose LLM provider id another enabled extension already registers.', retryable: false },
  EXT_SOURCE_INVALID: { title: 'The extension source is not valid', description: 'The extension source or package is not valid.', retryable: false },
  EXT_INTEGRITY: { title: 'The extension snapshot failed its integrity check', description: 'The extension snapshot failed its integrity check.', retryable: false },
  EXT_MANIFEST_INVALID: { title: 'The extension manifest is not valid', description: 'The manifest is not valid: setup not deterministic, registering after it returns, a schema JSON Schema cannot express, over 5 MB, an unknown manifestVersion, or drift at load.', retryable: false },
  EXT_REQUIRES_MISSING: { title: 'Required types or components are missing', description: 'Required types or components are not provided by enabled extensions.', retryable: false },
  EXT_IN_USE: { title: 'The extension is in use', description: 'Uninstalling while enabled, or disabling while another enabled extension requires it.', retryable: false },
  EXT_QUARANTINED: { title: 'The extension is quarantined', description: 'The extension is quarantined.', retryable: false },
  EXT_ROLLBACK_BLOCKED: { title: 'The data schema does not allow this rollback', description: 'The data schema does not allow this rollback.', retryable: false },
  EXT_GRANTS_REQUIRED: { title: 'The new version needs new grants', description: 'A reload needs new grants.', retryable: false },
  SCHEMA_TOO_NEW: { title: 'The stored data is newer than this code', description: 'The stored data is newer than this code.', retryable: false },
  MIGRATION_FAILED: { title: 'A data migration failed', description: 'A data migration failed.', retryable: false },
  CONFIRMATION_EXPIRED: { title: 'The confirmation expired or the staged content changed', description: 'The preview token expired or the staged bytes changed.', retryable: true },
  DAEMON_CONFLICT: { title: 'Another kernel owns this home folder', description: 'Another kernel owns the lock of this home folder.', retryable: false },
  HOME_INVALID: { title: 'The home folder holds other files', description: 'The home folder holds other files but no kvman.db.', retryable: false },
  HOST_FORBIDDEN: { title: 'The request Host or Origin is not allowed', description: 'A bad Host or Origin, or a refused Sec-Fetch-Site.', retryable: false },
  NOT_FOUND: { title: 'The resource does not exist', description: 'An unknown message id, route, or extension, or a subscription for a stream with no open connection.', retryable: false },
  PORT_UNAVAILABLE: { title: 'No port is free for the kernel', description: 'No port is free in 4173–4199, or the --port given is taken.', retryable: false },
  KERNEL_STOPPING: { title: 'The kernel is shutting down', description: 'A request arrived during shutdown.', retryable: true },
  INTERNAL: { title: 'Unexpected error', description: 'An unexpected error; the details are in the log.', retryable: true },
} as const satisfies Record<string, KernelErrorDefinition>;

export type KernelErrorCode = keyof typeof kernelErrors;
