// 03 §3.8's "who may send" column for the kernel types built so far, as far as views need it (ADR 0157):
// - `any`: every sender (including "any for its own"), so every view;
// - `admin`: an administrator; views whose owner holds kernel.admin (with `user` and `kernel.cancel`);
// - `user`: a person only; views whose owner holds kernel.admin;
// - `grant`: power-granting, reached only through openGrantDialog;
// - `llm`: the llm capability of an extension; never a view's target, a person does not call models.
export type KernelSender = 'any' | 'admin' | 'user' | 'grant' | 'llm';

export const kernelSenders: ReadonlyMap<string, KernelSender> = new Map<string, KernelSender>([
  ['kernel.health.get', 'any'],
  ['kernel.schema.get', 'any'],
  ['kernel.validate', 'any'],
  ['kernel.extensions.list', 'any'],
  ['kernel.extension.get', 'any'],
  ['kernel.workspaces.list', 'any'],
  ['kernel.workspace.get', 'any'],
  ['kernel.workspace.preset.get', 'any'],
  ['kernel.presets.list', 'any'],
  ['kernel.preset.get', 'any'],
  ['kernel.preset.current.get', 'any'],
  ['kernel.preset.import.preview', 'any'],
  ['kernel.preset.export.get', 'any'],
  ['kernel.config.get', 'any'],
  ['kernel.trust.preview', 'any'],
  ['kernel.subscribers.list', 'any'],
  ['kernel.processes.list', 'any'],
  ['kernel.llm.providers.list', 'any'],
  ['kernel.llm.models.list', 'any'],
  ['kernel.llm.defaults.get', 'any'],
  ['kernel.llm.usage.get', 'any'],
  ['kernel.llm.tokens.count', 'llm'],
  ['kernel.messages.list', 'admin'],
  ['kernel.workspace.open', 'admin'],
  ['kernel.workspace.rename', 'admin'],
  ['kernel.workspace.forget', 'user'],
  ['kernel.workspace.preview.create', 'admin'],
  ['kernel.trust.grant', 'grant'],
  ['kernel.trust.revoke', 'admin'],
  ['kernel.extension.stage', 'admin'],
  ['kernel.extension.install', 'admin'],
  ['kernel.extension.enable', 'grant'],
  ['kernel.extension.disable', 'admin'],
  ['kernel.extension.reload', 'grant'],
  ['kernel.extension.rollback', 'admin'],
  ['kernel.extension.unquarantine', 'user'],
  ['kernel.extension.uninstall', 'user'],
  ['kernel.preset.import', 'grant'],
  ['kernel.preset.apply.stage', 'admin'],
  ['kernel.preset.apply', 'grant'],
  ['kernel.preset.update', 'grant'],
  ['kernel.preset.save', 'admin'],
  ['kernel.preset.delete', 'admin'],
  ['kernel.config.set', 'admin'],
  ['kernel.secret.set', 'admin'],
  ['kernel.secret.clear', 'admin'],
  ['kernel.cancel', 'admin'],
  ['kernel.shutdown', 'user'],
  ['kernel.llm.complete', 'llm'],
  ['kernel.llm.models.refresh', 'admin'],
  ['kernel.llm.defaults.set', 'admin'],
  ['kernel.notifications.list', 'admin'],
  ['kernel.notifications.count', 'any'],
  ['kernel.notification.read', 'user'],
  ['kernel.notification.dismiss', 'user'],
  ['kernel.notifications.read-all', 'user'],
  ['kernel.notifications.mute', 'user'],
  ['kernel.message.retry', 'admin'],
]);
